# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('idade', models.IntegerField()),
                ('nome_responsavel', models.CharField(max_length=200)),
                ('contato', models.CharField(max_length=11)),
                ('data_de_atendimento', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
